### PR TITLE
Add until date to OAI harvesters

### PR DESCRIPTION
**Pull request by erinspace**

### CODE REVIEW

**Comment by chrisseto** [comment]
Could you possibly write a test for this?

**Comment by chrisseto** [comment]
lgtm.
Final thoughts @fabianvf ?

**Comment by fabianvf** [comment]
Did you still intend to add it for the other harvesters in this PR, or will you do it separately @erinspace?

If separately, the :+1:

**Comment by chrisseto** [comment]
It may not be relevant to other harvesters.

**Comment by fabianvf** [comment]
most (all?) other providers support this feature. I think it would be better to have a unified way to interact with the harvesters.

**Comment by erinspace** [comment]
most of the harvesters do support a range, but not all.

**Pull request merged**
