### PR TITLE
Python 3 port

### LINKED ISSUE #171: Python 3 support
this would be great!

### PR DESCRIPTION
**Pull request by jamesturk**
all tests seem to pass on 2.7 and 3.4

this touches *a lot* so should definitely be eyed with tons of suspicion 

closes #171

### CODE REVIEW

**Comment by fabianvf** [comment]
Let me know if you need any help/support getting the changes we discussed on Sunday in. Don't worry about the speed of validation for now, that is a separate issue.

**Comment by jamesturk** [comment]
thanks. I'm on a trip and away from a laptop for a couple of weeks. I think
the main thing is replacement of http pretty in that one test with mock
like all the others

**Comment by jamesturk** [comment]
I can get to it in a week or two but if someone else wants to that'd be
cool too

**Comment by erinspace** [comment]
I'm on it! Thanks so much @jamesturk :)

**Pull request merged**
