### PR TITLE
Processing -> Storage

### PR DESCRIPTION
**Pull request by fabianvf**

### CODE REVIEW

**Comment by chrisseto** [comment]
Can https://github.com/fabianvf/scrapi/pull/123 be closed?

**Comment by fabianvf** [comment]
yeah, if you want them to both be in the same PR. May want to just merge #123 instead though, then this diff will just get smaller. Not sure why I branched off #123 here.

**Comment by chrisseto** [comment]
Could you redefine `BaseProcessor`
Would backend be a better name for this/these module(s)?

**Comment by fabianvf** [comment]
We can continue this discussion later.

**Pull request closed without merging**
